In [2]:
import torch

In [4]:
a = torch.empty(1)
print(a)
a = torch.rand(5,5)
print(a)

tensor([0.])
tensor([[0.5635, 0.4655, 0.9792, 0.1349, 0.9582],
        [0.0546, 0.2557, 0.9855, 0.2333, 0.1781],
        [0.2646, 0.9627, 0.3199, 0.0298, 0.4558],
        [0.2520, 0.6581, 0.2265, 0.8045, 0.5531],
        [0.7804, 0.6219, 0.0826, 0.8597, 0.5841]])


In [6]:
x = torch.rand(3,3)
print(x)
x.add_(1)
print(x)

tensor([[0.6500, 0.1286, 0.5379],
        [0.7473, 0.3957, 0.3412],
        [0.4528, 0.5113, 0.2565]])
tensor([[1.6500, 1.1286, 1.5379],
        [1.7473, 1.3957, 1.3412],
        [1.4528, 1.5113, 1.2565]])


In [14]:
a = torch.ones(5,5, dtype=torch.float16)
print(a)
print(a.dtype)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float16)
torch.float16


In [19]:
a = torch.rand(5,5)
print(a.size())
print(a.shape)

torch.Size([5, 5])
torch.Size([5, 5])


In [21]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.add(a, b)
c = a + b 
print(c)

tensor([[0.9998, 0.9556],
        [0.2529, 1.0973]])


In [23]:
a = torch.rand(2, 2)
print(a)
a.mul_(3)
print(a)

tensor([[0.9321, 0.9102],
        [0.6241, 0.2610]])
tensor([[2.7964, 2.7307],
        [1.8722, 0.7829]])


In [24]:
c = torch.sub(a, b)
print(c)

tensor([[1.8400, 1.8008],
        [1.7477, 0.0873]])


In [25]:
c = torch.div(a, b)
print(c)

tensor([[ 2.9240,  2.9368],
        [15.0414,  1.1254]])


In [28]:
# slicing
a = torch.rand(3, 2)
print(a)
print(a[:,0])
print(a[0,0].item())

tensor([[0.5442, 0.6283],
        [0.5443, 0.6604],
        [0.3103, 0.0788]])
tensor([0.5442, 0.5443, 0.3103])
0.5442017316818237


In [33]:
# Reshaping a matrix

a = torch.rand(4, 4)
print(a)
b = a.view(8,2)
print(b)
b = a.view(-1, 8) # this will automatically determine the nrow for the given ncol
print(b.size())

tensor([[0.7180, 0.6531, 0.4384, 0.7611],
        [0.2674, 0.6475, 0.8807, 0.0058],
        [0.5240, 0.5478, 0.0100, 0.6841],
        [0.8044, 0.5089, 0.7527, 0.3257]])
tensor([[0.7180, 0.6531],
        [0.4384, 0.7611],
        [0.2674, 0.6475],
        [0.8807, 0.0058],
        [0.5240, 0.5478],
        [0.0100, 0.6841],
        [0.8044, 0.5089],
        [0.7527, 0.3257]])
torch.Size([2, 8])


In [46]:
#  converting numpy array to torch tensor and the opposite
import numpy as np
a = torch.rand(5)
print(a)
print(type(a))
b = a.numpy()
print(b)
print(type(b))


# If the tensor is on the CPU, such as this machine, then both a and b will share the same memory location
# so, changing a will automatically change the b

a.add_(1)
print(a)
print(b)

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
a+=1
print(a)
print(b)




tensor([0.0433, 0.8911, 0.3847, 0.9138, 0.6152])
<class 'torch.Tensor'>
[0.04329294 0.89110273 0.3846705  0.9137605  0.6151658 ]
<class 'numpy.ndarray'>
tensor([1.0433, 1.8911, 1.3847, 1.9138, 1.6152])
[1.043293  1.8911028 1.3846705 1.9137604 1.6151658]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [59]:
# how to check if torch saves on GPU:
if torch.cuda.is_available():
    print('Cuda available')
    device = torch.device('cuda')
    print(device)
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y # this operation will be much faster if we had GPU and with cuda toolkit installed
    z.numpy() # And again, if we had GPU this will produce an error, since numpy can work only CPU
else:
    y = torch.ones(5)
    x = torch.zeros(5)
    z = x + y # this operation will be much faster if we had GPU and with cuda toolkit installed
    print(z)
    z.numpy() # And again, if we had GPU this will produce an error, since numpy can work only CPU
    print(z)

# End of the tutorial 1  

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
